import type { PresentationSlide } from '@/content/presentation-slide-types';

export type { PresentationSlide, PresentationSlideLayout } from '@/content/presentation-slide-types';

const media = (name: string) => `/presentations/pointer/${name}`;

export const pointerPresentationSlides: PresentationSlide[] = [
  {
    id: 1,
    layout: 'title',
    title: 'پوینتر',
    subtitle: 'پلتفرم اجرای استراتژی و OKR',
    body: 'تهیه‌شده توسط: روشمند',
    image: media('image4.png'),
  },
  {
    id: 2,
    layout: 'content',
    title: 'هدف این ارائه',
    bullets: [
      'نمای کلی پلتفرم پوینتر برای مدیریت استراتژی و عملکرد',
      'منطق OKR و چرا سازمان‌ها به ساختار واحد نیاز دارند',
      'ماژول‌های اصلی: داشبورد، اهداف، تحلیل‌ها، سازمان‌ها و اقدامات',
      'گردش کار از تعریف هدف تا Check-in و گزارش‌گیری',
      'تمایز پوینتر نسبت به اکسل و ابزارهای پراکنده',
    ],
    body:
      'هدف، نشان دادن چگونگی تبدیل استراتژی به اهداف قابل اندازه‌گیری و پیگیری مستمر در یک پلتفرم یکپارچه است.',
  },
  {
    id: 3,
    layout: 'title',
    title: 'چرا OKR و برنامه‌ریزی ساختاریافته؟',
    image: media('image5.png'),
  },
  {
    id: 4,
    layout: 'content',
    title: 'مشکل رایج سازمان‌ها',
    bullets: [
      'عدم هم‌راستایی — تیم‌ها مسیر خود را می‌روند و اهداف جزیره‌ای تعریف می‌شوند',
      'شفاف نبودن اولویت‌ها — همه مشغول‌اند اما معلوم نیست کدام کار مهم‌تر است',
      'نبود پیگیری منظم — هدف نوشته می‌شود اما عدد و پیشرفت دقیق دیده نمی‌شود',
      'پراکندگی در اکسل — نسخه‌های مختلف، گزارش‌گیری سخت، Cascade ناممکن',
    ],
    body:
      'پوینتر این فاصله بین «نوشتن هدف» و «اجرای منظم و قابل اندازه‌گیری» را پر می‌کند — با Alignment، Check-in و تصویر یکپارچه از وضعیت سازمان.',
  },
  {
    id: 5,
    layout: 'title',
    title: 'پوینتر چیست؟',
    subtitle: 'از استراتژی تا اجرا — در یک پلتفرم',
    image: media('image4.png'),
  },
  {
    id: 6,
    layout: 'split',
    imageBg: 'white',
    title: 'پلتفرم اجرای استراتژیک',
    bullets: [
      'ثبت ساختارمند Objective و Key Result',
      'اتصال اهداف سازمانی و تیمی (Alignment)',
      'تعریف اقدام، مسئول و مهلت اجرا',
      'Check-in دوره‌ای و نمایش وضعیت On Track / At Risk',
      'Dashboard و Analytics برای تصویر یکپارچه',
    ],
    body: 'پوینتر آرزو را به عدد، عدد را به اقدام و اقدام را به پیشرفت قابل مشاهده تبدیل می‌کند.',
    image: media('image4.png'),
  },
  {
    id: 7,
    layout: 'title',
    title: 'ورود و Tenant',
    image: media('image1.png'),
  },
  {
    id: 8,
    layout: 'split',
    imageLayout: 'row',
    imageBg: 'white',
    title: 'شروع کار در پوینتر',
    bullets: [
      'ورود امن با ایمیل و رمز عبور سازمانی',
      'انتخاب Tenant — هر Tenant فضای کاری مستقل با داده جداگانه',
      'پس از انتخاب، داشبورد با اطلاعات همان سازمان بارگذاری می‌شود',
      'امکان تعویض Tenant در هر زمان از نوار کناری',
    ],
    images: [media('image1.png'), media('image2.png'), media('image3.png')],
  },
  {
    id: 9,
    layout: 'title',
    title: 'داشبورد',
    image: media('image4.png'),
  },
  {
    id: 10,
    layout: 'split',
    imageBg: 'white',
    title: 'نمای کلی OKR و عملکرد',
    bullets: [
      'کارت‌های خلاصه: کل اهداف، میانگین پیشرفت، نتایج کلیدی، فعالیت اخیر',
      'نمایش پیشرفت هر هدف با نوار درصد و وضعیت',
      'اقدامات باز و تکمیل‌شده — با اولویت و مهلت',
      'خوراک فعالیت اخیر و Check-inهای دوره‌ای',
      'دسترسی سریع: ایجاد هدف، تحلیل‌ها، مدیریت تیم‌ها',
    ],
    image: media('image4.png'),
  },
  {
    id: 11,
    layout: 'title',
    title: 'اهداف و نتایج کلیدی',
    image: media('image5.png'),
  },
  {
    id: 12,
    layout: 'split',
    imageLayout: 'row',
    imageBg: 'white',
    title: 'مدیریت Objectives و Key Results',
    bullets: [
      'فهرست، Gantt، درخت سلسله‌مراتب و Grid',
      'فیلتر بر اساس وضعیت، مالک، سازمان و دوره',
      'فرم ایجاد هدف: نام، سازمان، KR، نقش‌ها (Owner، Contributor، Approver)',
      'Roll-up و اهداف خصوصی برای سطوح مختلف سازمان',
    ],
    images: [media('image5.png'), media('image14.png')],
  },
  {
    id: 13,
    layout: 'title',
    title: 'تحلیل‌ها',
    image: media('image6.png'),
  },
  {
    id: 14,
    layout: 'split',
    imageBg: 'white',
    title: 'Analytics Dashboard',
    bullets: [
      'فیلتر چندبعدی: دوره، سازمان، دسته، برچسب، هدف و KR',
      'تب‌های Dashboard، Trends، Scores، Performance، Details',
      'کارت‌های پیشرفت اهداف و نتایج کلیدی',
      'جدول عملکرد تیم با امتیاز، انحراف زمانی و وضعیت',
      'خروجی داده و گزارش PDF',
    ],
    image: media('image6.png'),
  },
  {
    id: 15,
    layout: 'title',
    title: 'سازمان‌ها و کاربران',
    image: media('image7.png'),
  },
  {
    id: 16,
    layout: 'split',
    imageLayout: 'row',
    imageBg: 'white',
    title: 'ساختار سازمانی و دسترسی',
    bullets: [
      'سازمان، تیم و Chart — با سلسله‌مراتب والد-فرزند',
      'Cascade اهداف از سطح کلان به واحدها و تیم‌ها',
      'مدیریت کاربران: نقش Admin/Member، دعوت و مجوزها',
      'نقش‌های Boss، Representative، Approver و Monitor',
    ],
    images: [media('image7.png'), media('image8.png'), media('image15.png')],
  },
  {
    id: 17,
    layout: 'title',
    title: 'اقدامات و گردش کار',
    image: media('image9.png'),
  },
  {
    id: 18,
    layout: 'split',
    imageLayout: 'row',
    imageBg: 'white',
    title: 'از Kanban تا تأیید',
    bullets: [
      'تخته Kanban: Not Started، In Progress، Completed',
      'کارتابل تأیید اهداف و گردش کارهای در انتظار',
      'اعلان‌های OKR، تأییدها و به‌روزرسانی پیشرفت',
      'فرم اقدام متصل به Key Result و Objective',
    ],
    images: [media('image9.png'), media('image10.png'), media('image16.png')],
  },
  {
    id: 19,
    layout: 'split',
    imageLayout: 'row',
    imageBg: 'white',
    title: 'اعلان‌ها و تنظیمات',
    bullets: [
      'اعلان‌های خوانده/نخوانده با فیلتر نوع و اولویت',
      'تنظیمات پروفایل و امنیت حساب',
      'تنظیمات سیستم: تقویم، زبان، برچسب‌ها و دسته‌بندی‌ها',
      'چندمستاجری و حاکمیت داده در سطح Tenant',
    ],
    images: [media('image11.png'), media('image12.png'), media('image13.png')],
  },
  {
    id: 20,
    layout: 'content',
    title: 'چرا پوینتر متفاوت است؟',
    bullets: [
      'یکپارچگی — اهداف، KR، اقدامات و تحلیل در یک مدل داده',
      'Alignment واقعی — اتصال عمودی اهداف سازمانی و تیمی',
      'Check-in منظم — وضعیت On Track / At Risk قبل از پایان فصل',
      'Cascade سازمانی — شکست هدف کلان به واحدها با ساختار درختی',
      'جایگزین اکسل — بدون نسخه پراکنده، با گزارش و داشبورد زنده',
    ],
    body:
      'برخلاف صفحه‌گسترده یا ابزارهای جدا از هم، پوینتر چرخه کامل برنامه‌ریزی تا پیگیری را در یک محیط واحد پوشش می‌دهد.',
  },
  {
    id: 21,
    layout: 'title',
    title: 'سپاسگزاریم',
    subtitle: 'پوینتر — پلتفرم استراتژی و عملکرد',
    body: 'برای دمو و استقرار با روشمند تماس بگیرید.',
    image: media('image4.png'),
  },
];
